# Generated by Django 5.1.6 on 2025-03-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.JSONField(blank=True, default=dict, help_text="User's profile picture of different sizes", null=True),
        ),
    ]
