# Generated by Django 5.1.6 on 2025-03-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text="User's bio or description.", max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', help_text='Controls profile visibility: public or private.', max_length=10),
        ),
    ]
