# Generated by Django 5.1.6 on 2025-03-13 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the follow was created.')),
                ('followed', models.ForeignKey(help_text='The user being followed.', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='Followed')),
                ('follower', models.ForeignKey(help_text='The user who is following another user.', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Follower')),
            ],
            options={
                'verbose_name': 'Follow',
                'verbose_name_plural': 'Follows',
                'indexes': [models.Index(fields=['follower'], name='follows_fol_followe_1fd088_idx'), models.Index(fields=['followed'], name='follows_fol_followe_1802cd_idx')],
                'constraints': [models.UniqueConstraint(fields=('follower', 'followed'), name='unique_follow'), models.CheckConstraint(condition=models.Q(('follower', models.F('followed')), _negated=True), name='no_self_follow')],
            },
        ),
    ]
