# Generated by Django 5.1.6 on 2025-05-25 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('denied', 'Denied'), ('cancelled', 'Cancelled')], default='pending', help_text='Status of the follow request.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the request was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of when the request was last updated.')),
                ('requester', models.ForeignKey(help_text='The user sending the follow request.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requester')),
                ('target', models.ForeignKey(help_text='The user receiving the follow request.', on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL, verbose_name='Target')),
            ],
            options={
                'verbose_name': 'Follow Request',
                'verbose_name_plural': 'Follow Requests',
                'indexes': [models.Index(fields=['requester', 'status'], name='follows_fol_request_c4ef32_idx'), models.Index(fields=['target', 'status'], name='follows_fol_target__121fd2_idx')],
                'constraints': [models.UniqueConstraint(fields=('requester', 'target'), name='unique_follow_request'), models.CheckConstraint(condition=models.Q(('requester', models.F('target')), _negated=True), name='no_self_request')],
            },
        ),
    ]
