# Generated by Django 5.1.6 on 2025-05-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follows', '0002_followrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='is_super_follower',
            field=models.BooleanField(default=False, help_text='Indicates if the follower is a super follower, granting access to private posts.'),
        ),
    ]
