"""
Django settings for scrawl project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os 
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()  # This loads environment variables from the .env file


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-esgt)pstnse33_#f!s8(bp)_)w_*zr)&9*_=(t&#cmw&_@bln)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', 'localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    # 'django.contrib.postgres',
    # My apps
    'users',   # Users app
    'posts',   # Posts app
    'follows', # Follows app
    'feed',    # Feed app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'scrawl.core.monitoring.middleware.APIMetricsMiddleware',
 
]

ROOT_URLCONF = 'scrawl.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scrawl.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    
        
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),  # From .env
        'USER': os.getenv('POSTGRES_USER'),  # From .env
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),  # From .env
        'HOST': os.getenv('DB_HOST', 'db'),  # Defaults to 'db' if not set in .env
        'PORT': os.getenv('DB_PORT', '5432'),
    }
        
    
}

# Redis URL for direct client usage (e.g., in feed_service.py)
REDIS_URL = os.getenv("REDIS_URL", "redis://redis:6379/1")
# Redis Cache Configuration
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://redis:6379/1"),  # Fallback if .env missing
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Kafka Configuration
KAFKA = {
    'BOOTSTRAP_SERVERS': os.getenv('KAFKA_BROKER', 'drf_scrawl_kafka:9092'),
    'SECURITY_PROTOCOL': 'PLAINTEXT',
    'API_VERSION': (2, 3, 0)
}


# Rate Limiting Configuration
RATE_LIMIT_MIDDLEWARE = {
    'enabled': True,
    'apply_ip_limits': True,
    'apply_user_limits': True,
    'exempt_superusers': True,
    'fail_open': True,
    'add_headers': True,
    'log_violations': True,
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        # Existing formatter
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        # ELK JSON formatter
        'elk_json': {
            '()': 'scrawl.core.monitoring.logging.ELKFormatter',
            'format': '%(levelname)s %(name)s %(message)s'
        },
    },
    'handlers': {
        # Existing handlers
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'api_metrics': {
            'class': 'logging.FileHandler',
            'filename': 'api_metrics.log',
            'formatter': 'verbose'
        },
        # ELK handler for structured logs (Custom TCP)
        'elk_tcp': {
            'class': 'scrawl.core.monitoring.logging.ELKTCPHandler',
            'host': 'drf_scrawl_logstash',
            'port': 5000,
            'formatter': 'elk_json',
        },
        # ELK file handler (backup if Logstash is down)
        'elk_file': {
            'class': 'logging.FileHandler',
            'filename': 'elk_logs.json',
            'formatter': 'elk_json',
        },
    },
    'loggers': {
        # Existing logger
        'scrawl.api_metrics': {
            'handlers': ['console', 'api_metrics'],
            'level': 'INFO',
            'propagate': False,
        },
        # ELK logger for structured logging
        'scrawl.elk': {
            'handlers': ['elk_tcp', 'elk_file', 'console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Security events logger
        'scrawl.security': {
            'handlers': ['elk_tcp', 'elk_file', 'console'],
            'level': 'WARNING',
            'propagate': False,
        },
        # Enhanced Django loggers for ELK
        'django.request': {
            'handlers': ['elk_tcp', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'users.auth.EmailBackend',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),  # 1-day expiry
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Optional: refresh token lasts longer
    'BLACKLIST_AFTER_ROTATION': True,
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # Keeping this default as fallback
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'# Put this at the bottom of your settings.py
AUTH_USER_MODEL = 'users.User'